In [1]:
import numpy as np

def kron(*matrices):
    result = matrices[0]
    for i in range(1, len(matrices)):
        result = np.kron(result, matrices[i])
    return result

X = np.matrix([[0, 1], [1, 0]])
Y = np.matrix([[0, -1j], [1j, 0]])
Z = np.matrix([[1, 0], [0, -1]])
I = np.eye(2)

hamiltonian = 0
paulis = [X, Y, Z]

for pau in paulis:
    hamiltonian = hamiltonian + kron(pau, I, pau) + kron(pau, pau, I) + kron(I, pau, pau)

print(hamiltonian.real)



[[ 3.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -1.  2.  0.  2.  0.  0.  0.]
 [ 0.  2. -1.  0.  2.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.  2.  2.  0.]
 [ 0.  2.  2.  0. -1.  0.  0.  0.]
 [ 0.  0.  0.  2.  0. -1.  2.  0.]
 [ 0.  0.  0.  2.  0.  2. -1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  3.]]


1.  ['II', 'ZI', '-iYY']
2.  ['iXI']
3.  ['iXI', 'iZZ']
4.  ['YZ', '-iIX']
