In [1]:
import numpy as np
import sys
np.set_printoptions(threshold=sys.maxsize)

In [2]:
pos = np.array([[1,1,0,0,0,0],[1,0,1,0,0,0],[1,0,0,1,0,0],[1,0,0,0,0,1],[0,1,1,0,0,0],[0,1,0,1,0,0],[0,1,0,0,1,0],[0,0,1,0,1,0],[0,0,1,0,0,1]])




In [3]:
nodo= [(0, 1),(1, 2),(2, 3),(3, 4),(4, 5),(5, 0),(0, 6),(1, 6),(1, 7),(2, 7),(2, 8),(3, 8),(3, 9),(4, 9),(4, 10),(5, 10),(5, 11),(0, 11)]

def nodoarm(nodo):
    graf = []
    for ele in nodo:
        zeros = np.zeros(12)
        for pos in ele:
            zeros[pos] = 1
        graf.append(list(zeros))    
    return np.array(graf)

In [4]:
pos=nodoarm(nodo)

In [5]:
# pos = np.array([[1,1,0],[1,0,1],[0,1,1]])
#pos = np.array([[1,1,0,0,0,0],[0,1,1,0,0,0],[0,0,1,1,0,0],[0,0,0,1,1,0],[0,0,0,0,1,1],[1,0,0,0,0,1]])

#pos = np.array([[1,1,0,0],[0,1,1,0],[0,0,1,1],[0,1,0,1],[1,0,1,0]])

array([[1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0.,

In [6]:
mapping = {0: 'I', 1: 'X'}
arr_letras = np.where(pos == 0, mapping[0], mapping[1])


In [7]:
Z = np.matrix([[1,0],[0,-1]])
X = np.matrix([[0,1],[1,0]])
Y = np.matrix([[0,-1j],[1j,0]])
I = np.matrix([[1,0],[0,1]])
H = np.matrix([[1,1],[1,-1]])

np.dot(H, X)

matrix([[ 1,  1],
        [-1,  1]])

In [8]:
q = pos.shape[1]
pauli =[X,Y,Z]

ham = np.zeros((2**q,2**q))+1j*np.zeros((2**q,2**q))
for pau in pauli:
    for po in pos:
        tira = np.array([[1]])
        for i in range(q):
            tira =np.kron(tira, pau if po[i] ==1 else I)
        ham += tira

ham =ham.real        
        

In [9]:
p=np.linalg.eigh(Y)

In [10]:
p[1].T

matrix([[-0.70710678-0.j        ,  0.        +0.70710678j],
        [-0.70710678+0.j        ,  0.        -0.70710678j]])

In [11]:
ham==-18



In [17]:
a1, v1 = np.linalg.eigh(ham)

In [18]:
a1

array([-18.        , -18.        , -16.96132284, -16.96132284,
       -16.96132284, -16.94488902, -16.94488902, -16.94488902,
       -16.94488902, -16.94488902, -16.94488902, -16.92960648,
       -16.92960648, -16.92960648, -16.92960648, -16.92960648,
       -16.92960648, -16.80979384, -16.80979384, -16.80979384,
       -16.73525336, -16.72928939, -16.72928939, -16.56740607,
       -16.56740607, -16.31171211, -16.31171211, -16.31171211,
       -16.27540017, -16.27540017, -16.27540017, -16.27540017,
       -16.27540017, -16.27540017, -16.22588905, -16.04123404,
       -16.04123404, -16.04123404, -16.04123404, -16.04123404,
       -16.04123404, -15.65386148, -15.65386148, -15.65386148,
       -15.4600591 , -15.4600591 , -15.33076284, -15.33076284,
       -15.33076284, -15.31784115, -15.31784115, -15.31784115,
       -15.31784115, -15.31784115, -15.16684708, -15.16684708,
       -15.16684708, -15.16684708, -15.16684708, -15.16684708,
       -15.16684708, -15.16684708, -15.16684708, -15.16

In [19]:
h=v1.T



In [29]:
sum(h[64])

7.950020426450736e-16

In [529]:
ele =h[60].reshape((8,-1))

In [532]:
ele =h[58].reshape((8,-1))
import pandas as pd
df = pd.DataFrame(ele)
df


0       1       2       3       4       5       6       7
0  0.0000  0.0000 -0.0000 -0.0000  0.0000 -0.0000 -0.0000 -0.2236
1  0.0000 -0.0000 -0.0000 -0.2236 -0.0000 -0.2236 -0.2236  0.0000
2  0.0000 -0.0000 -0.0000 -0.2236 -0.0000 -0.2236 -0.2236 -0.0000
3 -0.0000 -0.2236 -0.2236 -0.0000 -0.2236 -0.0000  0.0000  0.0000
4 -0.0000 -0.0000 -0.0000 -0.2236 -0.0000 -0.2236 -0.2236 -0.0000
5 -0.0000 -0.2236 -0.2236  0.0000 -0.2236 -0.0000 -0.0000  0.0000
6 -0.0000 -0.2236 -0.2236  0.0000 -0.2236 -0.0000  0.0000  0.0000
7 -0.2236  0.0000 -0.0000  0.0000  0.0000  0.0000  0.0000  0.0000

In [506]:
np.dot(h[1],np.dot(ham,h[1]))

-17.99903531999999

In [491]:
h[1].round(3)

array([ 0.   ,  0.   , -0.   , -0.   ,  0.   ,  0.   , -0.   , -0.135,
        0.   , -0.   ,  0.   ,  0.   ,  0.   , -0.208,  0.343,  0.   ,
        0.   ,  0.   ,  0.   , -0.208, -0.   ,  0.343, -0.   ,  0.   ,
       -0.   ,  0.208, -0.   , -0.   , -0.343, -0.   , -0.   ,  0.   ,
       -0.   , -0.   , -0.   ,  0.343, -0.   , -0.   , -0.208,  0.   ,
        0.   ,  0.   , -0.343, -0.   ,  0.208,  0.   ,  0.   ,  0.   ,
       -0.   , -0.343,  0.208, -0.   ,  0.   ,  0.   , -0.   ,  0.   ,
        0.135,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ])

In [445]:


v1[abs(a1.round(3)+18)<10e-3].round(4).T

array([[-0.000e+00+0.j    , -0.000e+00+0.j    ],
       [ 0.000e+00+0.j    , -0.000e+00+0.j    ],
       [ 4.940e-02+0.j    ,  4.940e-02+0.j    ],
       [ 1.118e-01+0.j    ,  1.118e-01+0.j    ],
       [-0.000e+00+0.j    ,  1.250e-02+0.j    ],
       [ 1.070e-02+0.j    ,  1.070e-02+0.j    ],
       [ 5.900e-03+0.j    ,  5.900e-03+0.j    ],
       [ 2.900e-03+0.j    ,  2.900e-03+0.j    ],
       [-1.700e-03+0.j    , -1.700e-03+0.j    ],
       [-0.000e+00+0.j    , -0.000e+00+0.j    ],
       [-0.000e+00+0.j    ,  0.000e+00+0.j    ],
       [ 1.000e-04+0.j    ,  1.000e-04+0.j    ],
       [-0.000e+00+0.j    , -0.000e+00+0.j    ],
       [-0.000e+00+0.j    , -0.000e+00+0.j    ],
       [ 0.000e+00+0.j    ,  0.000e+00+0.j    ],
       [-0.000e+00+0.j    , -0.000e+00+0.j    ],
       [ 0.000e+00+0.j    ,  0.000e+00+0.j    ],
       [-0.000e+00+0.j    , -0.000e+00+0.j    ],
       [-0.000e+00+0.j    , -0.000e+00+0.j    ],
       [ 0.000e+00+0.j    ,  1.310e-02+0.j    ],
       [ 0.000e+00+0

In [431]:
save = v[abs(a.round(3)+18)<10e-3].round(4)

In [439]:
save

array([[ 0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
         0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
         0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
         0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
         0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
         0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
         0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
         0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
         0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
         0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
         0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
         0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
         0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
         0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
      

In [370]:
abs(save[0][1])

0.0

In [41]:

###ACA IMPRIME LOS QUE SON DISTINTOS DE 0

[print(i,bin(i),save[0][i]) if abs(save[0][i])> 0 else None for i in range(len(save[0]))] 

NameError: name 'save' is not defined

In [361]:
save

array([[ 0.    , -0.    ],
       [ 0.    , -0.    ],
       [ 0.    ,  0.    ],
       [ 0.    , -0.    ],
       [ 0.    , -0.    ],
       [ 0.    , -0.    ],
       [ 0.    ,  0.    ],
       [ 0.    ,  0.    ],
       [ 0.    ,  0.    ],
       [ 0.    ,  0.    ],
       [ 0.    , -0.    ],
       [ 0.    , -0.    ],
       [ 0.    ,  0.    ],
       [ 0.    ,  0.    ],
       [ 0.    , -0.    ],
       [ 0.    , -0.    ],
       [ 0.    , -0.    ],
       [ 0.    , -0.    ],
       [ 0.    ,  0.    ],
       [ 0.    , -0.    ],
       [ 0.    , -0.    ],
       [ 0.    ,  0.    ],
       [ 0.    , -0.    ],
       [ 0.    , -0.    ],
       [ 0.    , -0.    ],
       [ 0.    , -0.    ],
       [ 0.    ,  0.    ],
       [ 0.    , -0.    ],
       [ 0.    , -0.    ],
       [ 0.    , -0.    ],
       [ 0.    ,  0.    ],
       [ 0.    ,  0.    ],
       [ 0.    , -0.    ],
       [ 0.    ,  0.    ],
       [ 0.    , -0.    ],
       [ 0.    ,  0.    ],
       [ 0.    , -0.    ],
 

In [62]:
np.unique(p[1][6].round(3),return_counts=True)

(array([-0.39 , -0.31 , -0.236, -0.211, -0.197, -0.125, -0.108, -0.092,
        -0.073, -0.067, -0.063, -0.043, -0.041, -0.039, -0.033, -0.028,
        -0.027, -0.023, -0.021, -0.008, -0.006, -0.005, -0.004,  0.   ,
         0.001,  0.002,  0.007,  0.008,  0.011,  0.022,  0.032,  0.033,
         0.046,  0.047,  0.049,  0.054,  0.057,  0.102,  0.123,  0.203,
         0.231,  0.257,  0.265,  0.272,  0.387]),
 array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  2,  1,  1,  1,  1,  1,  1,
         2,  1,  1,  1,  1,  3, 12,  3,  2,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  2,  1,  1,  1,  1,  1,  1,  1,  1,  1], dtype=int64))

In [33]:
tira = np.array([[1]])

In [34]:
pau if po[0] ==1 else i

5

In [30]:
tira =np.kron(tira, pau if po[0] ==1 else i)
tira

array([[5]])