In [7]:
import numpy as np
import sys
np.set_printoptions(threshold=sys.maxsize)

In [4]:
pos = np.array([[1,1,0,0,0,0],[1,0,1,0,0,0],[1,0,0,1,0,0],[1,0,0,0,0,1],[0,1,1,0,0,0],[0,1,0,1,0,0],[0,1,0,0,1,0],[0,0,1,0,1,0],[0,0,1,0,0,1]])

In [68]:
pos = np.array([[1,1,0],[1,0,1],[0,1,1]])

In [16]:
mapping = {0: 'I', 1: 'X'}
arr_letras = np.where(pos == 0, mapping[0], mapping[1])


In [69]:
Z = np.matrix([[1,0],[0,-1]])
X = np.matrix([[0,1],[1,0]])
Y = np.matrix([[0,-1j],[1j,0]])
I = np.matrix([[1,0],[0,1]])

In [75]:
q = pos.shape[1]
pauli =[X,Y,Z]

ham = np.zeros((2**q,2**q))+1j*np.zeros((2**q,2**q))
for pau in pauli:
    for po in pos:
        tira = np.array([[1]])
        for i in range(q):
            tira =np.kron(tira, pau if po[i] ==1 else I)
        ham += tira

ham =ham.real        
        

In [80]:
ham

array([[ 3.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0., -1.,  2.,  0.,  2.,  0.,  0.,  0.],
       [ 0.,  2., -1.,  0.,  2.,  0.,  0.,  0.],
       [ 0.,  0.,  0., -1.,  0.,  2.,  2.,  0.],
       [ 0.,  2.,  2.,  0., -1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  2.,  0., -1.,  2.,  0.],
       [ 0.,  0.,  0.,  2.,  0.,  2., -1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  3.]])

In [77]:
a, v = np.linalg.eig(ham)

In [82]:
v[3]

array([ 0.40824829,  0.57735027, -0.18312503,  0.14052544, -0.24782273,
       -0.63449568,  0.        ,  0.        ])

In [67]:
np.linalg.norm(p[1][7])

1.012220641041958

In [62]:
np.unique(p[1][6].round(3),return_counts=True)

(array([-0.39 , -0.31 , -0.236, -0.211, -0.197, -0.125, -0.108, -0.092,
        -0.073, -0.067, -0.063, -0.043, -0.041, -0.039, -0.033, -0.028,
        -0.027, -0.023, -0.021, -0.008, -0.006, -0.005, -0.004,  0.   ,
         0.001,  0.002,  0.007,  0.008,  0.011,  0.022,  0.032,  0.033,
         0.046,  0.047,  0.049,  0.054,  0.057,  0.102,  0.123,  0.203,
         0.231,  0.257,  0.265,  0.272,  0.387]),
 array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  2,  1,  1,  1,  1,  1,  1,
         2,  1,  1,  1,  1,  3, 12,  3,  2,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  2,  1,  1,  1,  1,  1,  1,  1,  1,  1], dtype=int64))

In [33]:
tira = np.array([[1]])

In [34]:
pau if po[0] ==1 else i

5

In [30]:
tira =np.kron(tira, pau if po[0] ==1 else i)
tira

array([[5]])