In [1]:
import numpy as np
import sys
np.set_printoptions(threshold=sys.maxsize)

In [55]:
pos = np.array([[1,1,0,0,0,0],[1,0,1,0,0,0],[1,0,0,1,0,0],[1,0,0,0,0,1],[0,1,1,0,0,0],[0,1,0,1,0,0],[0,1,0,0,1,0],[0,0,1,0,1,0],[0,0,1,0,0,1]])

In [100]:
pos = np.array([[1,1,0],[1,0,1],[0,1,1]])

In [87]:
pos = np.array([[1,1,0,0],[0,1,1,0],[0,0,1,1],[1,0,0,1]])

In [62]:
pos = np.array([[1,1,0,0,0],[0,1,1,0,0],[0,0,1,1,0],[0,0,0,1,1],[1,0,0,0,1]])

In [70]:
pos = np.array([[1,1,0,0,0,0],[0,1,1,0,0,0],[0,0,1,1,0,0],[0,0,0,1,1,0],[0,0,0,0,1,1],[1,0,0,0,0,1]])

In [37]:
mapping = {0: 'I', 1: 'X'}
arr_letras = np.where(pos == 0, mapping[0], mapping[1])


In [38]:
Z = np.matrix([[1,0],[0,-1]])
X = np.matrix([[0,1],[1,0]])
Y = np.matrix([[0,-1j],[1j,0]])
I = np.matrix([[1,0],[0,1]])

In [101]:
q = pos.shape[1]
pauli =[X,Y,Z]

ham = np.zeros((2**q,2**q))+1j*np.zeros((2**q,2**q))
for pau in pauli:
    for po in pos:
        tira = np.array([[1]])
        for i in range(q):
            tira =np.kron(tira, pau if po[i] ==1 else I)
        ham += tira

ham =ham.real        
        

In [102]:
ham

array([[ 3.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0., -1.,  2.,  0.,  2.,  0.,  0.,  0.],
       [ 0.,  2., -1.,  0.,  2.,  0.,  0.,  0.],
       [ 0.,  0.,  0., -1.,  0.,  2.,  2.,  0.],
       [ 0.,  2.,  2.,  0., -1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  2.,  0., -1.,  2.,  0.],
       [ 0.,  0.,  0.,  2.,  0.,  2., -1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  3.]])

In [103]:
a, v = np.linalg.eigh(ham)
print(a.round(3))

[-3. -3. -3. -3.  3.  3.  3.  3.]


In [104]:
v.T.round(2)

array([[ 0.  ,  0.78, -0.2 ,  0.  , -0.59,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  , -0.78,  0.  ,  0.2 ,  0.59,  0.  ],
       [-0.  ,  0.23, -0.79,  0.  ,  0.57,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  , -0.23,  0.  ,  0.79, -0.57,  0.  ],
       [-0.  , -0.  , -0.  ,  0.58,  0.  ,  0.58,  0.58,  0.  ],
       [ 0.  ,  0.58,  0.58,  0.  ,  0.58,  0.  ,  0.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  1.  ]])

In [126]:
coso = [0, 0.78, -0.2, 0, -0.59, 0, 0, 0]
coso = [0, 0, 0, -0.15, 0, 0.85, -0.7, 0]

coso = [0, 0, 0, 1, 0, 0, -1, 0]

# coso = [0, 0, 0, 0, 0, 0, 0, 0,
#         0, 0, 1, 0, 0, 0, 0, 0]

mas = np.array([1,1])/np.sqrt(2)
menos = np.array([1,-1])/np.sqrt(2)

eig_Y1 = np.array([-1,1.j])/np.sqrt(2)
eig_Y2 = np.array([-1, -1.j])/np.sqrt(2)

# coso = np.kron(np.kron(mas, menos), menos)
print(coso)

coso = coso/np.linalg.norm(coso)
# coso = [0, 0, 0, 0, 0, 0, 0, 0,
#         0, 0, 1, 0, 0, 0, 0, 0]
print(sum(coso))

np.dot(np.dot(coso, ham), coso)

[0, 0, 0, 1, 0, 0, -1, 0]
0.0


-2.9999999999999996

In [50]:
v.T.round(3)[3]


array([ 0.   ,  0.   ,  0.   , -0.   ,  0.   ,  0.054, -0.054, -0.   ,
       -0.   ,  0.164, -0.164, -0.052, -0.   , -0.086, -0.14 , -0.   ,
       -0.   , -0.367, -0.148, -0.053,  0.016,  0.066,  0.003,  0.   ,
        0.499,  0.139,  0.049,  0.   ,  0.075,  0.   , -0.   ,  0.   ,
        0.   ,  0.148,  0.367,  0.075, -0.016,  0.049,  0.139,  0.   ,
       -0.499,  0.003,  0.066,  0.   , -0.053, -0.   ,  0.   ,  0.   ,
       -0.   , -0.14 , -0.086, -0.   , -0.052, -0.   , -0.   ,  0.   ,
        0.   ,  0.   ,  0.   ,  0.   , -0.   ,  0.   ,  0.   ,  0.   ])

In [19]:
psi = np.array([-8.46445714e-10+0.j, 5.26885074e-01+0.j,
                -7.01863375e-11+0.j, -7.06024740e-01+0.j,
                9.45704183e-10+0.j,  4.71584689e-01+0.j,
                1.26724135e-09+0.j, -3.91032780e-02+0.j]).real
np.linalg.norm(psi)

for vec in v:
    print(np.linalg.norm(vec - psi))

1.4142135614577958
1.5783626958631942
1.844994935582042
1.48517821948149
1.5351914124488664
1.0301833547342385
1.2740538628412061
1.4415986112457329


In [62]:
np.unique(p[1][6].round(3),return_counts=True)

(array([-0.39 , -0.31 , -0.236, -0.211, -0.197, -0.125, -0.108, -0.092,
        -0.073, -0.067, -0.063, -0.043, -0.041, -0.039, -0.033, -0.028,
        -0.027, -0.023, -0.021, -0.008, -0.006, -0.005, -0.004,  0.   ,
         0.001,  0.002,  0.007,  0.008,  0.011,  0.022,  0.032,  0.033,
         0.046,  0.047,  0.049,  0.054,  0.057,  0.102,  0.123,  0.203,
         0.231,  0.257,  0.265,  0.272,  0.387]),
 array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  2,  1,  1,  1,  1,  1,  1,
         2,  1,  1,  1,  1,  3, 12,  3,  2,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  2,  1,  1,  1,  1,  1,  1,  1,  1,  1], dtype=int64))

In [33]:
tira = np.array([[1]])

In [34]:
pau if po[0] ==1 else i

5

In [30]:
tira =np.kron(tira, pau if po[0] ==1 else i)
tira

array([[5]])